version: '3.1'

services:

  goose:
    container_name: lambot
    build: .
    volumes:
      - .:/src
    command: python app.py
    restart: always
    network_mode: "host"

    env_file:
      - ".env"

